import type {
  RawActivityRecord,
  RawDecision,
  RawDistributionBucket,
  RawLog,
  RawSession,
  RawTask,
  RawTaskHierarchy,
  RawTimelineEvent,
} from "./raw";

/** Page-oriented report model consumed by the report UI. */
export interface ReportData {
  metadata: ReportMetadata;
  overview: ReportOverview;
  sessions: ReportSessions;
  tasks: ReportTasks;
  logs: ReportLogs;
  decisions: ReportDecisions;
}

/** Report metadata, including values generated by the report processor. */
export interface ReportMetadata {
  project: {
    name: string;
    root: string;
    createdAt: Date;
    ctxVersion: string;
    timezone: string;
    dateTimeTemplate: string;
  };

  dataRange: {
    firstActivity: string;
    lastActivity: string;
  };

  generatedAt: Date;
  reportVersion: string;
}

/** Data needed to render the overview page. */
export interface ReportOverview {
  metrics: ReportOverviewMetrics;
  currentState: ReportCurrentState;
  recentActivity: RawActivityRecord[];
  timeline: RawTimelineEvent[];
}

/** Overview counters calculated from the source aggregates. */
export interface ReportOverviewMetrics {
  sessions: number;
  recordedDuration: number;
  activeDays: number;

  tasks: number;
  completedTasks: number;
  inProgressTasks: number;
  blockedTasks: number;
  pendingTasks: number;

  logs: number;
  decisions: number;

  /**
   * Report-owned calculations.
   */
  taskCompletionRate: number;
  taskOpenRate: number;
}

/** Entities currently active or most recently recorded. */
export interface ReportCurrentState {
  activeSession: RawSession | null;
  activeTask: RawTask | null;
  pendingTaskCount: number;
  blockedTaskCount: number;
  latestLog: RawLog | null;
  latestDecision: RawDecision | null;
}

/** Session data plus report-side session evaluations. */
export interface ReportSessions {
  records: RawSession[];
  statistics: ReportSessionStatistics;
  durationDistribution: RawDistributionBucket[];
  activity: ReportSessionActivity;
  gaps: ReportSessionGaps;
  evaluations: ReportSessionEvaluations;
}

/** Session statistics exposed to report pages. */
export interface ReportSessionStatistics {
  count: number;
  completedCount: number;
  activeCount: number;

  totalDuration: number;
  averageDuration: number;
  medianDuration: number;
  longestDuration: number;
  shortestDuration: number;
}

/** Session activity normalized for chart components. */
export interface ReportSessionActivity {
  firstStart: string;
  latestEnd: string;

  calendarDays: number;
  activeDays: number;
  inactiveDays: number;

  dailyCounts: ReportDailyValue[];
  dailyDurations: ReportDailyValue[];

  startByHour: ReportDistributionValue[];
  startByDayOfWeek: ReportDistributionValue[];

  averageStartTime: string;
  peakStartHour: number;
}

/** Session gaps normalized for summary cards and charts. */
export interface ReportSessionGaps {
  values: number[];

  average: number;
  median: number;
  longest: number;
  shortest: number;

  distribution: RawDistributionBucket[];
}

/** Lightweight measures of session continuity and recording density. */
export interface ReportSessionEvaluations {
  /**
   * Ratio of recorded work time to the elapsed calendar span.
   *
   * Exact formula belongs to the processor.
   */
  workContinuityRatio: number | null;

  /**
   * Lightweight report-side evaluation.
   */
  averageSessionsPerActiveDay: number | null;

  /**
   * Lightweight report-side evaluation.
   */
  averageSessionsPerCalendarDay: number | null;

  /**
   * Lightweight report-side evaluation.
   */
  averageRecordedTimePerActiveDay: number | null;

  /**
   * Lightweight report-side evaluation.
   */
  averageRecordedTimePerCalendarDay: number | null;
}

/** Task data plus report-side status evaluations. */
export interface ReportTasks {
  records: RawTask[];
  statistics: ReportTaskStatistics;
  statusDistribution: RawTaskStatusDistribution[];
  activity: ReportTaskActivity;
  hierarchy: RawTaskHierarchy;
  blocked: RawBlockedTask[];
  evaluations: ReportTaskEvaluations;
}

/** Task statistics exposed to report pages. */
export interface ReportTaskStatistics {
  count: number;

  completedCount: number;
  pendingCount: number;
  inProgressCount: number;
  blockedCount: number;
  openCount: number;

  rootCount: number;
  subtaskCount: number;
  maxDepth: number;

  averageCompletionDuration: number | null;
  medianCompletionDuration: number | null;
  longestCompletionDuration: number | null;
  shortestCompletionDuration: number | null;
}

/** Number of tasks in a particular status. */
export interface ReportTaskStatusDistribution {
  status: string;
  count: number;
}

/** Task activity normalized for chart components. */
export interface ReportTaskActivity {
  createdByDay: ReportDailyValue[];
  completedByDay: ReportDailyValue[];
}

/** Task hierarchy and integrity findings exposed to the report. */
export interface ReportTaskHierarchy {
  tree: RawTaskTreeNode[];
  orphans: string[];
  cycles: string[];
}

/** A blocked task and the reason it cannot proceed. */
export interface ReportBlockedTask {
  taskId: string;
  reason: string;
}

/** Percentages describing the task status mix. */
export interface ReportTaskEvaluations {
  completionRate: number | null;
  pendingRate: number | null;
  inProgressRate: number | null;
  blockedRate: number | null;
  openRate: number | null;
}

/** Log data plus report-side distribution evaluations. */
export interface ReportLogs {
  records: RawLog[];
  statistics: ReportLogStatistics;
  activity: ReportLogActivity;
  taskAnalysis: ReportLogTaskAnalysis;
  invalidReferences: RawInvalidReference[];
  evaluations: ReportLogEvaluations;
}

/** Log statistics exposed to report pages. */
export interface ReportLogStatistics {
  count: number;
  unlinkedCount: number;

  firstTimestamp: string;
  latestTimestamp: string;

  byType: Record<string, number>;

  issuesCount: number;
  attemptsCount: number;

  logsPerSession: number | null;
  logsPerTask: number | null;

  tasksWithLogs: number;
  tasksWithoutLogs: number;
}

/** Log activity normalized for chart components. */
export interface ReportLogActivity {
  byDay: ReportDailyValue[];
  byHour: ReportDistributionValue[];
}

/** Task-level log analysis normalized for report components. */
export interface ReportLogTaskAnalysis {
  mostLoggedTasks: ReportCountById[];
  tasksWithoutLogs: string[];
  issuesByTask: ReportCountById[];
  attemptsByTask: ReportCountById[];
  repeatedAttempts: ReportRepeatedAttempt[];
}

/** A task identifier and its associated log count. */
export interface ReportRepeatedAttempt {
  taskId: string;
  count: number;
}

/** Percentages and density measures derived from log statistics. */
export interface ReportLogEvaluations {
  /**
   * Percentage of all logs represented by each type.
   */
  typePercentages: Record<string, number>;

  /**
   * Percentage of logs that are issues.
   */
  issuePercentage: number | null;

  /**
   * Percentage of logs that are attempts.
   */
  attemptPercentage: number | null;

  /**
   * Issues for which no corresponding attempt exists.
   *
   * This is only populated if CTX supplies enough information
   * to establish the relationship.
   */
  issueWithoutAttemptPercentage: number | null;

  /**
   * Logs per recorded hour.
   */
  logsPerRecordedHour: number | null;
}

/** Decision data plus report-side topic and reference evaluations. */
export interface ReportDecisions {
  records: RawDecision[];
  statistics: ReportDecisionStatistics;
  references: ReportDecisionReferences;
  activity: ReportDecisionActivity;
  evaluations: ReportDecisionEvaluations;
}

/** Decision statistics exposed to report pages. */
export interface ReportDecisionStatistics {
  count: number;
  unlinkedCount: number;

  firstTimestamp: string;
  latestTimestamp: string;

  byTopic: ReportTopicCount[];
  repeatedTopics: string[];

  uncategorizedCount: number;

  byTag: ReportTagCount[];
}

/** Decision references grouped for report display. */
export interface ReportDecisionReferences {
  byType: Record<string, number>;

  tasksWithDecisions: string[];
  sessionsWithDecisions: string[];

  invalid: RawInvalidReference[];
}

/** Decision activity normalized for chart components. */
export interface ReportDecisionActivity {
  byDay: ReportDailyValue[];
}

/** Percentages and association measures derived from decision statistics. */
export interface ReportDecisionEvaluations {
  topicPercentages: Record<string, number>;
  tagPercentages: Record<string, number>;

  decisionsPerTask: number | null;
  decisionsPerSession: number | null;

  /**
   * Share of decisions belonging to the most frequent topic.
   */
  topTopicShare: number | null;
}

/** A numeric value associated with a calendar date. */
export interface ReportDailyValue {
  date: string;
  value: number;
}

/** A labeled count used by distribution charts. */
export interface ReportDistributionValue {
  label: string;
  count: number;
}

/** A count associated with an entity identifier. */
export interface ReportCountById {
  id: string;
  count: number;
}

/** A count associated with a topic. */
export interface ReportTopicCount {
  topic: string;
  count: number;
}

/** A count associated with a tag. */
export interface ReportTagCount {
  tag: string;
  count: number;
}

export type RawTaskStatusDistribution = {
  status: string;
  count: number;
};

export type RawTaskTreeNode = {
  taskId: string;
  children: string[];
};

export type RawBlockedTask = {
  taskId: string;
  reason: string;
};

export type RawInvalidReference = {
  type: string;
  id: string;
};
