import type { z } from "zod";

import type { SourceDataSchema } from "../schemas/source-data-schema";

type ParsedSourceData = z.infer<typeof SourceDataSchema>;
type SourceMetadata = ParsedSourceData["metadata"];
type SourceProject = SourceMetadata["project"];
type SourceSessions = ParsedSourceData["sessions"];
type SourceSession = SourceSessions["records"][number];
type SourceSessionStatistics = SourceSessions["statistics"];
type SourceDurationDistribution =
  SourceSessions["durationDistribution"][number];
type SourceSessionGaps = SourceSessions["gaps"];
type SourceTasks = ParsedSourceData["tasks"];
type SourceTask = SourceTasks["records"][number];
type SourceTaskStatistics = SourceTasks["statistics"];
type SourceTaskStatusDistribution = SourceTasks["statusDistribution"][number];
type SourceTaskTreeNode = SourceTasks["tree"][number];
type SourceBlockedTask = SourceTasks["blocked"][number];
type SourceLogs = ParsedSourceData["logs"];
type SourceLog = SourceLogs["records"][number];
type SourceLogStatistics = SourceLogs["statistics"];
type SourceLogTypeStatistics = SourceLogStatistics["byType"];
type SourceLogTaskAnalysis = SourceLogs["taskAnalysis"];
type SourceTaskLogCount = SourceLogTaskAnalysis["mostLoggedTasks"][number];
type SourceRepeatedAttempt = SourceLogTaskAnalysis["repeatedAttempts"][number];
type SourceDecisions = ParsedSourceData["decisions"];
type SourceDecision = SourceDecisions["records"][number];
type SourceDecisionStatistics = SourceDecisions["statistics"];
type SourceDecisionReferences = SourceDecisions["references"];
type SourceDecisionReferenceCounts = SourceDecisionReferences["byType"];
type SourceDecisionTopicCount = SourceDecisionStatistics["byTopic"][number];
type SourceDecisionTagCount = SourceDecisionStatistics["byTag"][number];
type SourceReference = NonNullable<SourceDecision["reference"]>;

/**
 * Represents the validated source payload generated by the CTX CLI.
 */
export interface SourceData extends ParsedSourceData {}

/**
 * Namespace containing the types that make up the CTX source payload.
 */
export namespace SourceData {
  export interface Metadata extends SourceMetadata {}

  export namespace Metadata {
    export interface Project extends SourceProject {}
  }

  export interface Sessions extends SourceSessions {}

  export namespace Sessions {
    export interface Record extends SourceSession {}
    export interface Statistics extends SourceSessionStatistics {}
    export interface Distribution extends SourceDurationDistribution {}
    export interface Gaps extends SourceSessionGaps {}
  }

  export interface Tasks extends SourceTasks {}

  export namespace Tasks {
    export interface Record extends SourceTask {}
    export interface Statistics extends SourceTaskStatistics {}
    export interface StatusDistribution extends SourceTaskStatusDistribution {}
    export interface TreeNode extends SourceTaskTreeNode {}
    export interface Blocked extends SourceBlockedTask {}
  }

  export interface Logs extends SourceLogs {}

  export namespace Logs {
    export interface Record extends SourceLog {}
    export interface Statistics extends SourceLogStatistics {}
    export interface TypeStatistics extends SourceLogTypeStatistics {}
    export interface TaskAnalysis extends SourceLogTaskAnalysis {}
    export interface TaskCount extends SourceTaskLogCount {}
    export interface RepeatedAttempt extends SourceRepeatedAttempt {}
  }

  export interface Decisions extends SourceDecisions {}

  export namespace Decisions {
    export interface Record extends SourceDecision {}
    export interface Statistics extends SourceDecisionStatistics {}
    export interface References extends SourceDecisionReferences {}
    export interface ReferenceCounts extends SourceDecisionReferenceCounts {}
    export interface TopicCount extends SourceDecisionTopicCount {}
    export interface TagCount extends SourceDecisionTagCount {}
  }

  export interface Reference extends SourceReference {}
}
